# Generated by Django 5.0.1 on 2024-01-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela_realizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('observacao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=13)),
                ('conta_contabil', models.CharField(max_length=100)),
                ('parcela_atual', models.IntegerField()),
                ('parcelas_total', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('natureza', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
