# Generated by Django 5.0.1 on 2024-01-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_realizado',
            name='data_liquidacao',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
