# Generated by Django 5.0.1 on 2024-01-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0003_remove_tabela_realizado_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_realizado',
            name='banco_liquidacao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
