# Generated by Django 5.0.1 on 2024-01-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0005_totaismes_realizado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotaisMes_realizado',
            new_name='Totais_mes_realizado',
        ),
    ]
