# Generated by Django 5.0.1 on 2024-02-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0007_alter_tabela_realizado_data_liquidacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_realizado',
            name='banco_liquidacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
