# Generated by Django 5.0.1 on 2024-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0008_alter_tabela_realizado_banco_liquidacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_realizado',
            name='transferencia_correlacao',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
