# Generated by Django 5.0.1 on 2024-02-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0009_tabela_realizado_transferencia_correlacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela_realizado',
            old_name='transferencia_correlacao',
            new_name='uuid_correlacao',
        ),
    ]
