# Generated by Django 5.0.1 on 2024-02-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0010_rename_transferencia_correlacao_tabela_realizado_uuid_correlacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_realizado',
            name='uuid_correlacao_parcelas',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
