# Generated by Django 5.0.1 on 2024-02-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizado', '0011_tabela_realizado_uuid_correlacao_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_realizado',
            name='banco_id_liquidacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
