# Generated by Django 5.0.1 on 2024-01-07 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentos',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 22, 22, 2, 979951, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
