# Generated by Django 5.0.1 on 2024-01-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0003_recebimentos_conta_contabil_recebimentos_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentos',
            name='natureza',
            field=models.CharField(default='Crédito', max_length=50),
            preserve_default=False,
        ),
    ]
