# Generated by Django 5.0.1 on 2024-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0006_rename_recebimentos_tabela_fluxo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_fluxo',
            name='valor',
            field=models.FloatField(),
        ),
    ]
