# Generated by Django 5.0.1 on 2024-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0007_alter_tabela_fluxo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_fluxo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
