# Generated by Django 5.0.1 on 2024-01-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0008_alter_tabela_fluxo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_fluxo',
            name='valor',
            field=models.IntegerField(verbose_name=float),
        ),
    ]
