# Generated by Django 5.0.1 on 2024-01-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0010_alter_tabela_fluxo_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaTemporaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('observacao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=13)),
                ('conta_contabil', models.CharField(max_length=100)),
                ('parcelas', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('natureza', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('movido_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
