# Generated by Django 5.0.1 on 2024-01-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0011_tabelatemporaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_fluxo',
            name='parcelas',
            field=models.CharField(max_length=50),
        ),
    ]
