# Generated by Django 5.0.1 on 2024-01-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0013_alter_tabelatemporaria_parcelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_formatada_fluxo', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
