# Generated by Django 5.0.1 on 2024-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0016_dataunica_total_credito_dataunica_total_debito'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotaisMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_formatada', models.CharField(max_length=8, unique=True)),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('saldo_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.DeleteModel(
            name='DataUnica',
        ),
    ]
