# Generated by Django 5.0.1 on 2024-01-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0019_bancos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaismes',
            name='fim_mes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totaismes',
            name='inicio_mes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totaismes',
            name='data_formatada',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
