# Generated by Django 5.0.1 on 2024-01-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0021_remove_tabela_fluxo_parcelas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelatemporaria',
            name='parcelas',
        ),
    ]
