# Generated by Django 5.0.1 on 2024-01-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0022_remove_tabelatemporaria_parcelas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotaisMes',
            new_name='Totais_mes_fluxo',
        ),
    ]
