# Generated by Django 5.0.1 on 2024-02-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0023_rename_totaismes_totais_mes_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
