# Generated by Django 5.0.1 on 2024-02-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0024_bancos_saldo_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='saldo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
